-- ENUM types
CREATE TYPE user_role AS ENUM ('EMPLOYEE', 'MANAGER');

CREATE TYPE request_status AS ENUM (
  'PENDING_MANAGER_APPROVAL',
  'MANAGER_APPROVED',
  'MANAGER_REJECTED',
  'ACTION_IN_PROGRESS',
  'CLOSED'
);

-- USER TABLE
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role user_role NOT NULL,
  manager_id INT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- REQUEST TABLE
CREATE TABLE IF NOT EXISTS requests (
  id SERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  created_by INT REFERENCES users(id) ON DELETE CASCADE,
  assigned_to INT REFERENCES users(id) ON DELETE CASCADE,
  manager_id INT REFERENCES users(id) ON DELETE CASCADE,
  status request_status NOT NULL DEFAULT 'PENDING_MANAGER_APPROVAL',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- REQUEST HISTORY TABLE
CREATE TABLE IF NOT EXISTS request_history (
  id SERIAL PRIMARY KEY,
  request_id INT REFERENCES requests(id) ON DELETE CASCADE,
  user_id INT REFERENCES users(id),
  action VARCHAR(50) NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);
